// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeedData.Data;

#nullable disable

namespace HomeTask_17_07_2023.Migrations
{
    [DbContext(typeof(GmDbContext))]
    [Migration("20230719065259_FirstMig")]
    partial class FirstMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusClient", b =>
                {
                    b.Property<int>("BussId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientsId")
                        .HasColumnType("integer");

                    b.HasKey("BussId", "ClientsId");

                    b.HasIndex("ClientsId");

                    b.ToTable("BusClient");
                });

            modelBuilder.Entity("CarClient", b =>
                {
                    b.Property<int>("CarsId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientsId")
                        .HasColumnType("integer");

                    b.HasKey("CarsId", "ClientsId");

                    b.HasIndex("ClientsId");

                    b.ToTable("CarClient");
                });

            modelBuilder.Entity("SeedData.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uzb Bus",
                            Speed = 100
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electro Bus",
                            Speed = 120
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fast Bus",
                            Speed = 160
                        });
                });

            modelBuilder.Entity("SeedData.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nexia 1",
                            Speed = 140
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nexia 2",
                            Speed = 180
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nexia 3",
                            Speed = 200
                        });
                });

            modelBuilder.Entity("SeedData.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bahriddin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "JasurBek"
                        },
                        new
                        {
                            Id = 3,
                            Name = "LazizBek"
                        });
                });

            modelBuilder.Entity("BusClient", b =>
                {
                    b.HasOne("SeedData.Models.Bus", null)
                        .WithMany()
                        .HasForeignKey("BussId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeedData.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarClient", b =>
                {
                    b.HasOne("SeedData.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("CarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeedData.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
